# Generated by Django 5.1.3 on 2024-11-16 07:12

import accounts.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[accounts.model_validators.validate_cpf_cnpj]),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
