# Generated by Django 5.1.3 on 2024-11-21 02:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizingImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_image', models.ImageField(upload_to='default_images')),
                ('optimized_image', models.ImageField(blank=True, null=True, upload_to='optimized_image')),
                ('status', models.CharField(choices=[('awaiting', 'Aguardando Processamento'), ('processing', 'Em Processamento'), ('processed', 'Processado')], default='awaiting', max_length=20)),
                ('mode', models.CharField(choices=[('Sync', 'Síncrono'), ('Async', 'Assíncrono')], default='Sync', max_length=10)),
                ('format', models.CharField(choices=[('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WEBP'), ('jpg', 'JPG')], default='jpeg', max_length=10)),
                ('compression', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complete_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
